name: Deploy preprod on dev branch update

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # Permet de déclencher le workflow manuellement
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.preprod_ftp_host }}
        username: ${{ secrets.preprod_ftp_user }}
        password: ${{ secrets.preprod_ftp_pass }}
        exclude: |
          **/.git*
          **/.git*/**
          ChampEmail.md
          Dockerfile
          docker-compose.yml
        server-dir: / 

  deploy:
    needs: web-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH Key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PREPROD_SSH_PRIVATE_KEY }}
        SSH_PASSPHRASE: ${{ secrets.PREPROD_SSH_PASSPHRASE }}
        SSH_KEY_NAME: ${{ secrets.PREPROD_SSH_KEY_NAME }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/$SSH_KEY_NAME
        chmod 600 ~/.ssh/$SSH_KEY_NAME
        eval $(ssh-agent -s)
        echo "$SSH_PASSPHRASE" | ssh-add ~/.ssh/$SSH_KEY_NAME

    - name: Test SSH and Path
      run: |
        ssh -T -o StrictHostKeyChecking=no ${{ secrets.PREPROD_SSH_USER }}@${{ secrets.PREPROD_SSH_HOST }} "pwd && whoami && ls -la ${{ secrets.PREPROD_SSH_PATH }}"

    - name: Run Composer commands
      run: |
        ssh -T -o StrictHostKeyChecking=no ${{ secrets.PREPROD_SSH_USER }}@${{ secrets.PREPROD_SSH_HOST }} << 'EOF'
          cd ${{ secrets.PREPROD_SSH_PATH }}
          composer install
          composer update
          composer dump-autoload
        EOF
